### ISSUE TITLE
[Boards] Delivery Plans show no rollup data

### ISSUE THREAD

**Issue by NenoLoje** [NenoLoje/AzureDevOpsWishlist#2]
### Current state

In a Delivery Plan, when using the _Show child rollup data_ option, the child data section does not show.

#### Screenshot

> 
![grafik](https://user-images.githubusercontent.com/13981145/188466347-a0631be0-fda0-4c0a-8539-10d74fbe7423.png)
> 
![AzBoards-DeliveryPlans](https://user-images.githubusercontent.com/13981145/188466385-0ccf9c30-91ba-4f30-9992-161c4817461c.png)

### Desired state

It should show the child rollup data or some indication that it cannot load the data.

**Comment by danhellem** [comment]
this is usaally because the AX service has hiccup. Refresh usually solves it. Or give it a day or two. If you still have issues you can email me and we can take a look and see if something is stuck

**Comment by NenoLoje** [comment]
Status update: A support request was created with Microsoft (SR 2209170050000194)

**Comment by NenoLoje** [comment]
**Status update:** The issue has been resolved.

**Resolution**:

> After our Produce Group team investigated the issue further, this issue happened due to latency in sync between TFS and Analytics. The job which is responsible to sync the data is Priority 7 which is of lower priority and there are multiple Priority 8 jobs (higher priority) running at that time. After completion of Priority 8 jobs, priority 7 jobs will be picked up by the system.
